Repository binlecode/example-git-hooks, pull requests merged in 2020-10, with the labels that each got.

#9 feat: #8 #hacktoberfest - add pre-commit hook ruby example
  README.md
  pre-commit.rb
Labels: enhancement, hacktoberfest

#11 feat: #10 - add hook installation file
  install_hooks.rb
Labels: hacktoberfest-accepted

#15 Feature/12 install hook script
  install_hooks.config.yml
  install_hooks.rb
  pre-commit
Labels: hacktoberfest, hacktoberfest-accepted, housekeeping

#17 Feature/12 add install removal
  .gitignore
  README.md
  install_hooks.rb
Labels: enhancement, hacktoberfest-accepted

#20 Fix prompt issue of interactive user input in a non-tty terminal env
  README.md
  commit-msg.kanbanize.rb
Labels: hacktoberfest, hacktoberfest-accepted

#21 Replaced raw string with symbols in Hash keys
  commit-msg.kanbanize.rb
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#23 better README and some code cleansing
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#22 Made commit message pattern configurable
  README.md
  commit-msg.config
  commit-msg.kanbanize.rb
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#26 update pre-commit with tab check
  pre-commit.filescan.sh
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#29 bug fix: yaml parsed hash symbol key not working
  commit-msg.kanbanize.rb
Labels: bug, hacktoberfest, hacktoberfest-accepted
